CREATE
EXTENSION IF NOT EXISTS postgis;

CREATE TABLE shops
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    address      VARCHAR(255),
    closing_time TIMESTAMP(6),
    email        VARCHAR(255),
    opening_time TIMESTAMP(6),
    phone_number VARCHAR(255),
    point        geography(Point, 4326)
);

CREATE TABLE users
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    avatar   VARCHAR(255),
    full_name VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    role     VARCHAR(255) NOT NULL,
    username VARCHAR(255) NOT NULL,
    phone_number VARCHAR(255) NOT NULL,
    address VARCHAR(255) NOT NULL,
    CONSTRAINT users_role_check
        CHECK (role IN ('OWNER', 'OPERATOR', 'CUSTOMER')),
    CONSTRAINT uk_users_username UNIQUE (username)
);

CREATE TABLE queues
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    current_size INTEGER,
    remain_time  INTEGER,
    size         INTEGER,
    shop_id      BIGINT,
    CONSTRAINT fk_queues_shop
        FOREIGN KEY (shop_id) REFERENCES shops (id)
);

CREATE TABLE orders
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    estimate_time_minutes INTEGER,
    order_status          VARCHAR(255),
    total_amount          DOUBLE PRECISION,
    queue_id              BIGINT,
    shop_id               BIGINT,
    user_id               BIGINT,
    CONSTRAINT orders_order_status_check
        CHECK (order_status IN ('WAITING', 'PROCESSING', 'COMPLETED', 'CANCELED')),
    CONSTRAINT fk_orders_queue
        FOREIGN KEY (queue_id) REFERENCES queues (id),
    CONSTRAINT fk_orders_shop
        FOREIGN KEY (shop_id) REFERENCES shops (id),
    CONSTRAINT fk_orders_user
        FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE stocks
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    estimate_time_minute INTEGER,
    name                 VARCHAR(255),
    price                DOUBLE PRECISION,
    shop_id              BIGINT,
    CONSTRAINT fk_stocks_shop
        FOREIGN KEY (shop_id) REFERENCES shops (id)
);

CREATE TABLE order_stocks
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stock_number INTEGER,
    order_id     BIGINT,
    stock_id     BIGINT,
    CONSTRAINT fk_order_stocks_order
        FOREIGN KEY (order_id) REFERENCES orders (id),
    CONSTRAINT fk_order_stocks_stock
        FOREIGN KEY (stock_id) REFERENCES stocks (id)
);

-- Create Admin user
INSERT INTO users (avatar,
                   full_name,
                   username,
                   password,
                   role,
                   phone_number,
                   address)
VALUES (NULL,
        'Owner',
        'admin',
        '$2a$10$vAnzoY.cXntzL/iBUJlnE.9uL2OV6qTIl8c93AyDEn/WjCSWf3EFe',
        'OWNER',
        '0297432353',
        'Ha Noi, Viet Nam');